### ISSUE TITLE
getAuthContextForSubject: Cannot get AuthContext without subject

### ISSUE THREAD

**Issue by umashri4490** [umashri4490/uma#1]
Hi @gschueler

Im received this this error previous version 2.7 . So, now i switched to Rundeck 2.9.2-1.
But still am facing the same issue . could you please let us know how to proceed proceed further.

Upgrading to 2.10.1 will resolve this issue?.

INFO  ExecutionService: updated scheduled Execution
INFO  ExecutionService: updated scheduled Execution
INFO  ExecutionUtilService: Execution successful: 194910 in project PVH-Prod
INFO  ExecutionService: updated scheduled Execution
INFO  ExecutionUtilService: Execution successful: 194911 in project PVH-Prod
INFO  ExecutionService: updated scheduled Execution
ERROR GrailsExceptionResolver: RuntimeException occurred when processing request: [GET] /project/PVH-Prod/job/show/af67cd1e-6189-41a6-8944-1e790d95f8db
getAuthContextForSubject: Cannot get AuthContext without subject. Stacktrace follows:
java.lang.RuntimeException: getAuthContextForSubject: Cannot get AuthContext without subject
        at rundeck.services.FrameworkService.getAuthContextForSubject(FrameworkService.groovy:603)
        at rundeck.services.FrameworkService.userAuthContext(FrameworkService.groovy:590)
        at rundeck.filters.ProjectSelectFilters$_closure1$_closure2$_closure3.doCall(ProjectSelectFilters.groovy:77)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
:

**Comment by greg** [comment]
hi, please double check usernames before @-mentioning people, it's annoying

**Comment by umashri4490** [comment]
@

**Comment by umashri4490** [comment]
Hi @gschueler

Could you please help us on this
